### ISSUE TITLE
Logged-in facebook capturing works on webrecorder.io, but not on the local pywb-webrecorder

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb-webrecorder#5]
Locally, a 'Please Log In' alert box is shown constantly when recording locally.

This might be because facebook checks for https protocol?

**Comment by ikreymer** [comment]
Fixed from pywb >= 0.8.3, issue was with `secure` cookies, which would be dropped in http replay.
For now, dropping the `secure` on replay/proxy
