### ISSUE TITLE
wrongly rewritten URLs

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb-webrecorder#8]
This relatively simple page's image URLs are rewritten wrongly:
http://speichern-unter.net/alle-einreichungen.html

**Comment by ikreymer** [comment]
It has to do with the `<base>` tag which always makes things confusing... (For certain sites, rewriting it needs to be disabled, but not for others.. It can be toggled with `rewrite_base). For this site, it should be rewritten.. But, the trailing slash is missing, so it was being rewritten to `<base href="http://localhost:8080/record/http://speichern-unter.net">`, thus dropping the host part.
Will add a fix.

**Comment by ikreymer** [comment]
Fixed in pywb 0.8.3
